plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.49-beta' apply false
    
    // FIX FOR GRADLE 9 + INTELLIJ:
    // Forces a Groovy 4 compatible version of the idea-ext plugin
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1' apply false
}